base_url = "https://dronewa.rs/"
home = "home.md"
# theme = "zola.386"

default_language = "en"
title = "Press tab to play"
description = "Or use your mouse / cursor.  Whatever."

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]


[extra]
author = "Dronecon Hackathon"
year = "Begun, the drone wars have."

keywords = "drone wars, hackathon, hacking, cyber"
theme_color = "#000084"
zola386_menu = [
  {path="home", name="Home"},
  {path="details", name="Details"},
  {path="interest", name="Interest Form"},
  {path="poster", name="Poster"},
  {path="onepager", name="OnePager"},
  {path="resources", name="Resources"},
  {path="categories", name="Categories"},
  {path="tags", name="Tags"},
  {path="githubrepo", name="Files"},
  {path="howto", name="How to"},
  {path="404", name="Game Over"},
  {path="respawn", name="Startx"}
]

### THIRD PARTY
# google_analytics = ""
# disqus = "disqus-user"

### SOCIAL MEDIA
image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
linkedin_user = "rustd"
  github_user = "trustdan"
# gitlab_user = ""

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Event"
label_date = ""
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
